language: php

php:
  - 5.6
  - 7.0
  - 7.1

env:
  - COMPOSER_FLAGS=--prefer-lowest
  - COMPOSER_FLAGS=

matrix:
  include:
    - php: 7.1
      env: PHPUNIT_FLAGS=--coverage-text
  exclude:
    - php: 7.1
      env: COMPOSER_FLAGS=
  fast_finish: true

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer update --no-interaction --no-suggest --prefer-dist $COMPOSER_FLAGS

script:
  - vendor/bin/phpunit $PHPUNIT_FLAGS
  - vendor/bin/behat -vv -f progress
